version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "lucas"
      MYSQL_DATABASE: "hyperf"

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    name: hyperf-skeleton
